### ISSUE TITLE
 Image recognition.

### ISSUE THREAD

**Issue by Jostle786** [Mahedi-61/MIU_Fall_2019#1]
How can i mention four limitations
using K-Nearest Neighbor,  sir? i can't understand. please clear me , sir.

**Comment by Mahedi-61** [comment]
First,  you have to understand the algorithm. Read the notes.
You can find more about KNN algorithm [here](https://medium.com/@YearsOfNoLight/intro-to-image-classification-with-knn-987bc112f0c2) and play the demo [here](http://vision.stanford.edu/teaching/cs231n-demos/knn/). 

If you know the algorithm, you can easily find the cons of it. 
 
a. KNN classifier takes no time to train since all that is required is to store the training data. However, the computational cost at test time is very high, since classifying a test example requires a comparison to every single training example.  

b. Images are high-dimensional objects (i.e. they often contain many pixels), and calculating distances over high-dimensional spaces is very counter-intuitive. (that's called **curse of dimensionality** problem)

c. Moreover, the original image can be shifted, rotated, tilted, brighten or darken which are unintuitive for the KNN classifier. since the pixel-wise distance does not correspond at all to perceptual or semantic similarity. 

d. In the KNN classifier there exists a strong effect of the background rather than semantic class differences. 

e. For image classification, space complexity is the main issue for the KNN classifier since it has to store all the train images in the model.

**Comment by Jostle786** [comment]
thanks sir..
