### ISSUE TITLE
Python-3.8 (in Linux) Installation Problem

### ISSUE THREAD

**Issue by mzminhaz5683** [Mahedi-61/MIU_Fall_2019#3]
I have used windows-8.1 operating system as my OS and python-3.8(x64) as project environment.
I have done some code on that. But at run time I have faced OS issues. So I have to move on linux.
I have installed Linuk-kali-17 (GNOME Terminal - 3.26.1). It has python 2.7 build-in.
But I need python-3.8 to run my existing codes. It seems like when I try to install 3.8 or upgrade then it says permission denied. I can't find any solution even can't uninstall python-2.7 (which is build-in).... What can I do...?

**Comment by Mahedi-61** [comment]
It's not a good idea to uninstall Python-2.7. 
Because, it may cause dependency issues since many applications in the Linux system inherently depend on Python-2.7. 

Try to install Python-3.8 as a separate application. You can do the following 
```
wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz && tar -xvf Python-3.8.0.tgz
cd Python-3.8.0
./configure
make
sudo make altinstall
```

After installation, type `python3.8` on the terminal. 
Let me know whether it works or not. 

You can aslo make it `python3` by making an alias variable in the` ~/.bashrc` file.  try
```
sudo nano ~/.bashrc
alias python3="python3.8"
```
Then press Ctrl+O   +   Ctrl+M   +   Ctrl+X

**Comment by mzminhaz5683** [comment]
Thank you sir. It works. I have installed it. But after that I loss pip... I have seen many youtube videos. but I can't find pip3 even no longer pip is there in pc

**Comment by Mahedi-61** [comment]
First, try typing in terminal `pip3.8`

If it's not there then try this
`sudo apt-get install python3-pip`
Then again, try typing in terminal `pip3.8`

If that doesn't work. then try this. 
```
wget https://bootstrap.pypa.io/get-pip.py
python3.8 get-pip.py
```
If that run properly, then instead of pip3 you have to use every time `python3.8 -m pip `
And of course,  `sudo` at the first

For example, if you want to install TensorFlow, try
```
sudo python3.8 -m pip install tensorflow==1.4.0
sudo python3.8 -m pip install  keras
```

**Comment by mzminhaz5683** [comment]
Sir.. thanks... but not working for me.. It seems like 'zlib' library is not there. I also try to work with virtualenv ... but that also required 'zlib' library... But it's not in python3.8 ... I check that through import zlib ...but doesn't work.... but python 2.7 and even 3.6 have that library... don't understand what to do nowww

**Comment by Mahedi-61** [comment]
sudo apt-get install libgcrypt11-dev zlib1g-dev

**Comment by mzminhaz5683** [comment]
Thank u sir... Full complete now... Working in Virtualenv...
