### ISSUE TITLE
Error problem ,

### ISSUE THREAD

**Issue by Ariful491** [Mahedi-61/MIU_Fall_2019#7]
![mehedi sir](https://user-images.githubusercontent.com/52754507/68991395-98c76400-0888-11ea-9e7e-ef4148634e7c.png)

**Comment by mzminhaz5683** [comment]
It's because python doesn't record where a package was loaded from. You are attempting to run the file at it's own location and it becomes it's system directory. But you have to run the file from the outer path at least when the path contain the location of config.py & src/preprocess.py.... 
You can do it by opening terminal at "WORK-Place" and then run the code "python -m WORK-PLACE.src.preprocess"...You have to do the work manually (typing in tarminal everytime.)

Thanks...

Or, you can do like me... I am using run.sh to run the command.
![Screenshot from 2019-11-16 17-46-44](https://user-images.githubusercontent.com/52498840/68992718-332fa380-0899-11ea-85ad-b76ac5d91403.png)

**Comment by Ariful491** [comment]
may be those command doesn't work for windows ..

**Comment by mzminhaz5683** [comment]
oh...sorry.... i was thinking you are using linux...wait... i will check for windows...

**Comment by mzminhaz5683** [comment]
The cosde is same... I also check in windows 
... 
You have to reach the folder which contains both  "config.py" & "src".... then run the code as
python -m WORK-PLACE.src.preprocess
it's for you....

![Screenshot (26)](https://user-images.githubusercontent.com/52498840/68993831-8fe58b00-08a6-11ea-8d99-7e0ce05463a5.png)

**Comment by Mahedi-61** [comment]
What a conversation. However, it's
`from .. import config`

You have put a space befor and after `..`

**Comment by Ariful491** [comment]
![sir](https://user-images.githubusercontent.com/52754507/68994939-8b26d400-08b2-11ea-94cb-752aab71addb.png)
 sir, again showing error  .

**Comment by Mahedi-61** [comment]
run this as @mzminhaz5683 suggested in your `semester 12` directory 

`python -m work-place.src.preproces`
