### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ibrahim-kardi** [Mahedi-61/MIU_Fall_2019#8]
how can i overcome this error 
![Screenshot from 2019-11-17 00-09-59](https://user-images.githubusercontent.com/25303964/68997312-262da700-08cf-11ea-8451-326fedfe4d7c.png)

**Comment by Mahedi-61** [comment]
It's not clear from your image. 
Paste the complete log of your error traceback. Especially the last portion.

**Comment by ibrahim-kardi** [comment]
![Screenshot from 2019-11-17 20-40-13](https://user-images.githubusercontent.com/25303964/69008967-c7be0280-097a-11ea-9318-816648b3d8ac.png)

**Comment by Mahedi-61** [comment]
Yea, Just that I thought. 
It happens due to the version mismatch between Keras and Tensorflow backend. 

If you install Tensorflow old version (less than 2.0) You have to install Keras version less than 2.3
Try to uninstall Keras first then install Keras any version less than 2.3. 
For example 

`sudo pip3 install keras==2.2.0`

**Comment by ibrahim-kardi** [comment]
جزاك اللهُ خيرًا

**Comment by Mahedi-61** [comment]
يجب أن تحاول بذل قصارى جهدك قبل الحصول على بخيبة أمل
